### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by fkinghatesigningup** [Tempus/The-Disciple#21]
Exception: com.badlogic.gdx.utils.GdxRuntimeException: Error creating sound com.badlogic.gdx.backends.lwjgl.audio.Ogg$Sound for file: audio/sound/STS_SleepJingle_3c_NewMix_v1.ogg
03:01:03.364 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Error creating sound com.badlogic.gdx.backends.lwjgl.audio.Ogg$Sound for file: audio/sound/STS_SleepJingle_3c_NewMix_v1.ogg
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newSound(OpenALAudio.java:119) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newSound(OpenALAudio.java:41) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.Sfx.initSound(Sfx.java:87) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.Sfx.play(Sfx.java:29) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.SoundMaster.play(SoundMaster.java:431) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.audio.SoundMaster.play(SoundMaster.java:444) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.vfx.campfire.CampfireSleepEffect.playSleepJingle(CampfireSleepEffect.java:135) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.vfx.campfire.CampfireSleepEffect.update(CampfireSleepEffect.java:76) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2734) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:893) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_161]
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newSound(OpenALAudio.java:117) ~[desktop-1.0.jar:?]
	... 12 more
Caused by: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method) ~[?:1.8.0_161]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:1.8.0_161]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:1.8.0_161]
	at org.lwjgl.BufferUtils.createByteBuffer(BufferUtils.java:60) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.backends.lwjgl.audio.OggInputStream.<init>(OggInputStream.java:110) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.backends.lwjgl.audio.OggInputStream.<init>(OggInputStream.java:98) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.backends.lwjgl.audio.Ogg$Sound.<init>(Ogg.java:66) ~[desktop-1.0.jar:?]
	at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_161]
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newSound(OpenALAudio.java:117) ~[desktop-1.0.jar:?]
	... 12 more

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.OutOfMemoryError: unable to create new native thread
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at io.sentry.connection.AsyncConnection.send(AsyncConnection.java:96)
	at io.sentry.SentryClient.sendEvent(SentryClient.java:135)
	at io.sentry.SentryClient.sendEvent(SentryClient.java:176)
	at io.sentry.Sentry.capture(Sentry.java:177)
	at io.sentry.log4j2.SentryAppender.append(SentryAppender.java:133)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1994)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1966)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:739)
	at com.megacrit.cardcrawl.core.ExceptionHandler.handleException(ExceptionHandler.java:16)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:539)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by Tempus** [comment]
This is an unknown memory leak. Were you running other mods at the same time as mine?

**Comment by fkinghatesigningup** [comment]
just base mod and the disciple
