### ISSUE TITLE
Mod CTD after starting a game

### ISSUE THREAD

**Issue by KongMD-Steam** [Tempus/The-Disciple#4]
## Expected Behavior
Pressing 'Play' starts a new game.

## Actual Behavior
The game crashes after pressing 'Play'. This is being caused by the newest version of BaseMod, v3.1.0. I do not get this crash on v3.0.2. Stack trace:

```
12:30:49.562 INFO unlock.UnlockTracker> Already seen: SecondHand
12:30:49.562 INFO unlock.UnlockTracker> Already seen: PatternShift
12:30:49.595 INFO dungeons.AbstractDungeon> CardRng Counter: 0
12:30:49.617 INFO dungeons.AbstractDungeon> [BOSS] Hexaghost
12:30:49.618 INFO basemod.BaseMod> Adding Custom Events...
12:30:49.639 INFO dungeons.AbstractDungeon> INIT CARD POOL
Exception: java.lang.NullPointerException
12:30:49.641 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.InitializeCardPoolsSwitch.Insert(InitializeCardPoolsSwitch.java:58) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.initializeCardPools(AbstractDungeon.java:1571) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.<init>(AbstractDungeon.java:360) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:50) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1370) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:466) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.
```
## Mods active
1) BaseMod 3.1.0
2) The Disciple 0.9.3

**Comment by KongMD-Steam** [comment]
Closing. This was a bug with BaseMod and was fixed with release 3.1.1.
