### ISSUE TITLE
game crushes every time since ascension 10

### ISSUE THREAD

**Issue by RealZen79** [Tempus/The-Disciple#42]
Upon reaching the ascension 10 the game crushes every time when the button "embark" is pressed

**Comment by RealZen79** [comment]
it crushes even when ascension is unchecked, works without mode is on

**Comment by Tempus** [comment]
Yesterday, a patch released for Slay the Spire that broke characters. I updated to 0.9.7 to fix the issue. Please confirm that you are playing on the latest Slay the Spire patch, and on 0.9.7.

**Comment by RealZen79** [comment]
The game started to crush with patch 0.9.6 after Slay the Spire patch. The installation of 0.9.7 did not help. Now it crushes with any character when mode is on.
By the way, many thanks for the excellent work, I hope you manage to bring the mod to the end, despite the updates of the main game =)
Sorry for bad eanglish.

**Comment by RealZen79** [comment]
If it helps then that's what's going on in the ModTheSpire log, after button "embark" is pressed:

23:59:34.853 INFO dungeons.AbstractDungeon> Generating seeds: -6303991167252234581
23:59:35.506 INFO core.CardCrawlGame> PAUSE()
23:59:35.850 INFO basemod.BaseMod> publishPreStartGame
23:59:35.850 INFO basemod.BaseMod> hooking into character creation
23:59:35.850 INFO basemod.BaseMod> creating character CHRONO_CLASS
23:59:35.858 INFO unlock.UnlockTracker> Already seen: Chronometer
23:59:35.863 INFO unlock.UnlockTracker> Already seen: Chronometer
23:59:35.873 INFO chronomuncher.ChronoMod> Creating our character?
23:59:35.873 INFO unlock.UnlockTracker> Already seen: Chronometer
23:59:35.946 INFO unlock.UnlockTracker> Already seen: Strike_Br
23:59:35.946 INFO unlock.UnlockTracker> Already seen: Strike_Br
23:59:35.946 INFO unlock.UnlockTracker> Already seen: Strike_Br
23:59:35.946 INFO unlock.UnlockTracker> Already seen: Strike_Br
23:59:35.946 INFO unlock.UnlockTracker> Already seen: Defend_Br
23:59:35.947 INFO unlock.UnlockTracker> Already seen: Defend_Br
23:59:35.947 INFO unlock.UnlockTracker> Already seen: Defend_Br
23:59:35.947 INFO unlock.UnlockTracker> Already seen: Defend_Br
23:59:35.947 INFO unlock.UnlockTracker> Already seen: SecondHand
23:59:35.947 INFO unlock.UnlockTracker> Already seen: PatternShift
23:59:35.980 INFO dungeons.AbstractDungeon> CardRng Counter: 0
23:59:35.993 INFO unlock.UnlockTracker> Already seen: AscendersBane
23:59:36.001 INFO dungeons.AbstractDungeon> [BOSS] The Guardian
23:59:36.002 INFO basemod.BaseMod> Adding Custom Events...
23:59:36.017 INFO dungeons.AbstractDungeon> INIT CARD POOL

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/daily/DailyMods
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/daily/DailyMods
	at basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.InitializeCardPoolsSwitch.Insert(InitializeCardPoolsSwitch.java:42)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.initializeCardPools(AbstractDungeon.java:1561)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.<init>(AbstractDungeon.java:352)
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:50)
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1370)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:882)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:465)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.daily.DailyMods
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 9 more

**Comment by Tempus** [comment]
Crash log confirms you are missing the latest update for basemod, please update and enjoy the mod!

**Comment by RealZen79** [comment]
already done, thanks alot =)
