### ISSUE TITLE
Unknown error, not sure what caused this

### ISSUE THREAD

**Issue by AvangionQ** [Tempus/The-Disciple#63]
04:21:28.082 INFO helpers.File> Successfully saved file=C:\Games\Slay the Spire\preferences\HAKUMEN
04:21:28.123 INFO basemod.BaseMod> publish on post power apply
04:21:28.123 INFO basemod.BaseMod> powers modified
04:21:28.274 INFO basemod.BaseMod> publishPostExhaust
04:21:28.406 INFO basemod.BaseMod> publish on post power apply
04:21:28.407 INFO basemod.BaseMod> powers modified
04:21:29.100 INFO monsters.AbstractMonster> Disposing Atlas...
04:21:31.526 INFO basemod.BaseMod> publish on card use
04:21:31.526 INFO ThMod.ThMod> ThMod : Card used : strawberrySpire:Trickbox ; cost : 0
04:21:31.528 INFO ThMod.ThMod> typhoon-counter increased , now :5
04:21:31.528 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:31.531 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:31.560 INFO basemod.BaseMod> publish on post power apply
04:21:31.560 INFO basemod.BaseMod> powers modified
04:21:31.643 INFO basemod.BaseMod> publishPostExhaust
04:21:31.743 INFO basemod.BaseMod> publish on post power apply
04:21:31.743 INFO basemod.BaseMod> powers modified
04:21:34.745 INFO basemod.BaseMod> publish on card use
04:21:34.745 INFO ThMod.ThMod> ThMod : Card used : Strike_from_Beyond ; cost : 1
04:21:34.748 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:34.750 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:34.750 INFO guile.CombatFatigues> Strike from Beyond+
04:21:34.779 INFO basemod.BaseMod> publish on post power apply
04:21:34.779 INFO basemod.BaseMod> powers modified
04:21:34.896 INFO slimebound.SlimeboundMod> Patch hit.
04:21:35.430 INFO basemod.BaseMod> powers modified
04:21:35.763 INFO basemod.BaseMod> publish on post power apply
04:21:35.764 INFO basemod.BaseMod> powers modified
04:21:42.603 INFO basemod.BaseMod> ----------- Minion Before Attacking --------------
04:21:43.353 INFO unique.PoisonLoseHpAction> Head Louse HAS 38 HP.
04:21:43.503 INFO slimebound.SlimeboundMod> Patch hit.
04:21:43.620 INFO basemod.BaseMod> publishPreMonsterTurn
04:21:44.070 INFO basemod.BaseMod> publish on post power apply
04:21:44.070 INFO basemod.BaseMod> powers modified
04:21:44.420 INFO basemod.BaseMod> publish on post power apply
04:21:44.421 INFO basemod.BaseMod> powers modified
04:21:44.487 INFO basemod.BaseMod> publish on post power apply
04:21:44.488 INFO basemod.BaseMod> powers modified
04:21:44.538 INFO guile.CombatFatigues> gained_block_last_turn true
04:21:44.538 INFO guile.CombatFatigues> havent_attacked_last_turn false
04:21:44.540 INFO basemod.BaseMod> publishPostEnergyRecharge
04:21:44.671 INFO basemod.BaseMod> publish on post power apply
04:21:44.672 INFO basemod.BaseMod> powers modified
04:21:44.737 INFO basemod.BaseMod> powers modified
04:21:44.821 INFO basemod.BaseMod> powers modified
04:21:45.038 INFO basemod.BaseMod> powers modified
04:21:45.121 INFO basemod.BaseMod> powers modified
04:21:45.422 INFO basemod.BaseMod> powers modified
04:21:45.521 INFO basemod.BaseMod> publishPostDraw
Tilt-A-Whirl+ was drawn!=======================================
04:21:45.571 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:21:45.855 INFO basemod.BaseMod> publishPostDraw
Panic Button+ was drawn!=======================================
04:21:45.905 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:21:45.955 INFO basemod.BaseMod> publishPostDraw
Fear+ was drawn!=======================================
04:21:46.022 INFO slimebound.SlimeboundMod> Patch hit.
04:21:47.457 INFO basemod.BaseMod> publish on card use
04:21:47.457 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:21:47.459 INFO ThMod.ThMod> typhoon-counter increased , now :6
04:21:47.464 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:47.465 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:47.506 INFO basemod.BaseMod> publish on post power apply
04:21:47.507 INFO basemod.BaseMod> powers modified
04:21:47.807 INFO basemod.BaseMod> publish on post power apply
04:21:47.807 INFO basemod.BaseMod> powers modified
04:21:47.874 INFO basemod.BaseMod> publish on post power apply
04:21:47.875 INFO basemod.BaseMod> powers modified
04:21:48.440 INFO basemod.BaseMod> publish on card use
04:21:48.440 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:21:48.443 INFO ThMod.ThMod> typhoon-counter increased , now :7
04:21:48.446 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:48.446 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:48.658 INFO basemod.BaseMod> publish on post power apply
04:21:48.658 INFO basemod.BaseMod> powers modified
04:21:48.725 INFO basemod.BaseMod> publish on post power apply
04:21:48.725 INFO basemod.BaseMod> powers modified
04:21:53.828 INFO basemod.BaseMod> publish on card use
04:21:53.829 INFO ThMod.ThMod> ThMod : Card used : Clockwork:TiltAWhirl ; cost : -1
04:21:53.832 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:53.834 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:53.834 INFO guile.CombatFatigues> Tilt-A-Whirl+
04:21:54.196 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.199 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.363 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.363 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.512 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.513 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.663 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.663 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.830 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.830 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.980 INFO slimebound.SlimeboundMod> Patch hit.
04:21:54.980 INFO slimebound.SlimeboundMod> Patch hit.
04:21:55.080 INFO basemod.BaseMod> publishPostDraw
Arcane Healing+ was drawn!=======================================
04:21:55.147 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:21:55.197 INFO basemod.BaseMod> publishPostDraw
Lock'N'Load+ was drawn!=======================================
04:21:55.247 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:21:55.313 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:21:55.364 INFO basemod.BaseMod> publishPostDraw
Ssssneak+ was drawn!=======================================
04:21:55.414 INFO basemod.BaseMod> publish on post power apply
04:21:55.414 INFO basemod.BaseMod> powers modified
04:21:55.496 INFO basemod.BaseMod> publish on post power apply
04:21:55.497 INFO basemod.BaseMod> powers modified
04:21:55.714 INFO basemod.BaseMod> publish on post power apply
04:21:55.715 INFO basemod.BaseMod> powers modified
04:21:55.797 INFO basemod.BaseMod> publish on post power apply
04:21:55.797 INFO basemod.BaseMod> powers modified
04:21:57.415 INFO basemod.BaseMod> publish on card use
04:21:57.415 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:21:57.417 INFO ThMod.ThMod> typhoon-counter increased , now :8
04:21:57.421 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:57.423 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:57.465 INFO basemod.BaseMod> publish on post power apply
04:21:57.466 INFO basemod.BaseMod> powers modified
04:21:57.782 INFO basemod.BaseMod> publish on post power apply
04:21:57.783 INFO basemod.BaseMod> powers modified
04:21:57.848 INFO basemod.BaseMod> publish on post power apply
04:21:57.849 INFO basemod.BaseMod> powers modified
04:21:57.915 INFO basemod.BaseMod> publish on post power apply
04:21:57.916 INFO basemod.BaseMod> powers modified
04:21:58.366 INFO basemod.BaseMod> publish on card use
04:21:58.366 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:21:58.368 INFO ThMod.ThMod> typhoon-counter increased , now :9
04:21:58.371 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:58.371 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:58.566 INFO basemod.BaseMod> publish on post power apply
04:21:58.567 INFO basemod.BaseMod> powers modified
04:21:58.649 INFO basemod.BaseMod> publish on post power apply
04:21:58.650 INFO basemod.BaseMod> powers modified
04:21:58.716 INFO basemod.BaseMod> publish on post power apply
04:21:58.717 INFO basemod.BaseMod> powers modified
04:21:59.267 INFO basemod.BaseMod> publish on card use
04:21:59.267 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:21:59.271 INFO ThMod.ThMod> typhoon-counter increased , now :10
04:21:59.274 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:59.276 INFO chun_li.SpikyBracers> card has been chosen = false
04:21:59.467 INFO basemod.BaseMod> publish on post power apply
04:21:59.468 INFO basemod.BaseMod> powers modified
04:21:59.533 INFO basemod.BaseMod> publish on post power apply
04:21:59.534 INFO basemod.BaseMod> powers modified
04:21:59.600 INFO basemod.BaseMod> publish on post power apply
04:21:59.601 INFO basemod.BaseMod> powers modified
04:22:02.670 INFO basemod.BaseMod> publish on card use
04:22:02.670 INFO ThMod.ThMod> ThMod : Card used : hubris:Ssssneak ; cost : 0
04:22:02.672 INFO ThMod.ThMod> typhoon-counter increased , now :11
04:22:02.676 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:02.677 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:02.753 INFO basemod.BaseMod> publishPostDraw
Plastic Night+ was drawn!=======================================
04:22:02.804 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:22:02.853 INFO basemod.BaseMod> publish on post power apply
04:22:02.853 INFO basemod.BaseMod> powers modified
04:22:03.087 INFO slimebound.SlimeboundMod> Patch hit.
04:22:03.220 INFO basemod.BaseMod> publish on post power apply
04:22:03.220 INFO basemod.BaseMod> powers modified
04:22:03.287 INFO basemod.BaseMod> publish on post power apply
04:22:03.288 INFO basemod.BaseMod> powers modified
04:22:03.359 INFO basemod.BaseMod> publish on post power apply
04:22:03.360 INFO basemod.BaseMod> powers modified
04:22:04.137 INFO basemod.BaseMod> publish on card use
04:22:04.138 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:22:04.140 INFO ThMod.ThMod> typhoon-counter increased , now :12
04:22:04.143 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:04.143 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:04.338 INFO basemod.BaseMod> publish on post power apply
04:22:04.339 INFO basemod.BaseMod> powers modified
04:22:04.421 INFO basemod.BaseMod> publish on post power apply
04:22:04.421 INFO basemod.BaseMod> powers modified
04:22:04.488 INFO basemod.BaseMod> publish on post power apply
04:22:04.488 INFO basemod.BaseMod> powers modified
04:22:15.264 INFO slimebound.SlimeboundMod> Patch hit.
04:22:15.564 INFO slimebound.SlimeboundMod> Patch hit.
04:22:16.214 INFO basemod.BaseMod> ----------- Minion Before Attacking --------------
04:22:17.449 INFO unique.PoisonLoseHpAction> Head Louse HAS 20 HP.
04:22:17.599 INFO slimebound.SlimeboundMod> Patch hit.
04:22:17.700 INFO basemod.BaseMod> publishPreMonsterTurn
04:22:18.269 INFO basemod.BaseMod> publishPreMonsterTurn
04:22:18.617 INFO basemod.BaseMod> publishPreMonsterTurn
04:22:19.601 INFO guile.CombatFatigues> gained_block_last_turn true
04:22:19.601 INFO guile.CombatFatigues> havent_attacked_last_turn false
04:22:19.604 INFO basemod.BaseMod> publish on Player Lose Block
04:22:19.606 INFO basemod.BaseMod> publishPostEnergyRecharge
04:22:19.718 INFO basemod.BaseMod> powers modified
04:22:19.918 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:22:20.218 INFO basemod.BaseMod> publishPostDraw
Zap+ was drawn!=======================================
04:22:20.268 INFO basemod.BaseMod> publishPostDraw
Bandage Up+ was drawn!=======================================
04:22:20.318 INFO basemod.BaseMod> publishPostDraw
Static Discharge+ was drawn!=======================================
04:22:20.385 INFO basemod.BaseMod> publishPostDraw
I.O.U. was drawn!=======================================
04:22:22.019 INFO basemod.BaseMod> publish on card use
04:22:22.020 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:22:22.022 INFO ThMod.ThMod> typhoon-counter increased , now :13
04:22:22.025 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:22.028 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:22.220 INFO basemod.BaseMod> publish on post power apply
04:22:22.221 INFO basemod.BaseMod> powers modified
04:22:22.304 INFO basemod.BaseMod> publish on post power apply
04:22:22.304 INFO basemod.BaseMod> powers modified
04:22:22.370 INFO basemod.BaseMod> publish on post power apply
04:22:22.370 INFO basemod.BaseMod> powers modified
04:22:23.054 INFO basemod.BaseMod> publish on card use
04:22:23.054 INFO ThMod.ThMod> ThMod : Card used : ReplayTheSpireMod:IOU ; cost : -2
04:22:23.056 INFO ThMod.ThMod> typhoon-counter increased , now :14
04:22:23.059 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:23.061 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:23.109 INFO basemod.BaseMod> publish on post power apply
04:22:23.110 INFO basemod.BaseMod> powers modified
04:22:23.438 INFO basemod.BaseMod> publish on post power apply
04:22:23.438 INFO basemod.BaseMod> powers modified
04:22:23.521 INFO basemod.BaseMod> publish on post power apply
04:22:23.522 INFO basemod.BaseMod> powers modified
04:22:23.587 INFO basemod.BaseMod> publish on post power apply
04:22:23.588 INFO basemod.BaseMod> powers modified
04:22:24.305 INFO basemod.BaseMod> publish on card use
04:22:24.305 INFO ThMod.ThMod> ThMod : Card used : Zap ; cost : 0
04:22:24.307 INFO ThMod.ThMod> typhoon-counter increased , now :15
04:22:24.310 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:24.310 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:24.489 INFO basemod.BaseMod> publish on post power apply
04:22:24.489 INFO basemod.BaseMod> powers modified
04:22:24.571 INFO basemod.BaseMod> publish on post power apply
04:22:24.572 INFO basemod.BaseMod> powers modified
04:22:24.638 INFO basemod.BaseMod> publish on post power apply
04:22:24.639 INFO basemod.BaseMod> powers modified
04:22:25.222 INFO basemod.BaseMod> publish on card use
04:22:25.223 INFO ThMod.ThMod> ThMod : Card used : Bandage Up ; cost : 0
04:22:25.225 INFO ThMod.ThMod> typhoon-counter increased , now :16
04:22:25.227 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:25.228 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:25.539 INFO basemod.BaseMod> publishPostExhaust
04:22:25.639 INFO basemod.BaseMod> publish on post power apply
04:22:25.640 INFO basemod.BaseMod> powers modified
04:22:25.723 INFO basemod.BaseMod> publish on post power apply
04:22:25.723 INFO basemod.BaseMod> powers modified
04:22:25.790 INFO basemod.BaseMod> publish on post power apply
04:22:25.790 INFO basemod.BaseMod> powers modified
04:22:26.390 INFO basemod.BaseMod> publish on card use
04:22:26.390 INFO ThMod.ThMod> ThMod : Card used : Static Discharge ; cost : 1
04:22:26.393 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:26.395 INFO chun_li.SpikyBracers> card has been chosen = false
04:22:26.574 INFO basemod.BaseMod> publish on post power apply
04:22:26.574 INFO basemod.BaseMod> powers modified
04:22:26.657 INFO basemod.BaseMod> publish on post power apply
04:22:26.658 INFO basemod.BaseMod> powers modified
04:22:27.775 INFO basemod.BaseMod> publish on post power apply
04:22:27.778 INFO basemod.BaseMod> powers modified
04:22:27.841 INFO basemod.BaseMod> publish on post power apply
04:22:27.842 INFO basemod.BaseMod> powers modified
04:22:27.925 INFO basemod.BaseMod> publish on post power apply
04:22:27.925 INFO basemod.BaseMod> powers modified
Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
04:22:28.893 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at chronomuncher.patches.RetainCardSelectPatch.Postfix(RetainCardSelectPatch.java:42) ~[TheDisciple.jar:?]
	at com.megacrit.cardcrawl.screens.select.HandCardSelectScreen.open(HandCardSelectScreen.java:591) ~[?:?]
	at conspire.actions.FixedExhaustAction.update(FixedExhaustAction.java:71) ~[Conspire.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by Tempus** [comment]
Would you happen to be on the StS beta branch?

**Comment by AvangionQ** [comment]
That was on 3.6.3 ... the one available from github ... https://github.com/kiooeht/ModTheSpire/releases
